name: posrant
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  freezed_annotation: ^2.1.0
  json_annotation: ^4.7.0
  intl: ^0.18.1
  google_fonts: ^4.0.4
  material_design_icons_flutter: ^6.0.7096
  image_picker: ^0.8.5+3
  file_picker: ^5.2.2
  uuid: ^3.0.6
  flutter_image_compress: ^2.0.3
  cached_network_image: ^3.2.2
  permission_handler: ^10.0.2
  geolocator: ^9.0.2
  flutter_map: ^4.0.0
  carousel_slider: ^4.1.1
  flutter_rating_bar: ^4.0.1
  url_launcher: ^6.1.6
  blur: ^3.1.0
  flutter_svg: ^2.0.5
  custom_clippers: ^2.0.0
  badges: ^3.1.1
  flutter_markdown: ^0.6.12
  dotted_border: ^2.0.0+3
  faker_dart: ^0.1.11
  syncfusion_flutter_charts: ^21.2.4
  qr_flutter: ^4.0.0
  path_provider: ^2.0.11
  flutter_animate: ^4.1.1+1
  dio: ^5.0.1
  fluttertoast: ^8.2.2

  
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.3
  cloud_firestore: ^4.8.1
  google_sign_in: ^6.1.4
  firebase_storage: ^11.2.2
  
dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo_posrant.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

  flutter_test:
    sdk: flutter
flutter:
  assets: 
    - assets/
    - assets/images/cashless-payment.png
    - assets/images/fast-food.png
    - assets/images/point-of-sale.png
    - assets/images/banner-1.jpg
    - assets/images/banner-2.jpeg
    - assets/images/google.png
    - assets/images/table.png
    - assets/images/logo_posrant.png
  uses-material-design: true
